# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/uni/fyp/version8/muslim_soc/muslim_soc.cache/wt [current_project]
set_property parent.project_path D:/uni/fyp/version8/muslim_soc/muslim_soc.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/uni/fyp/version8/muslim_soc/muslim_soc.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog {
  D:/uni/fyp/version8/muslim_soc/muslim_soc.srcs/sources_1/imports/src/soc/uncore/i2c/rtl/i2c_master_defines.v
  D:/uni/fyp/version8/muslim_soc/muslim_soc.srcs/sources_1/imports/src/soc/uncore/ptc/ptc_defines.v
  D:/uni/fyp/version8/muslim_soc/muslim_soc.srcs/sources_1/imports/src/soc/uncore/uart/uart_defines.v
  D:/uni/fyp/version8/muslim_soc/muslim_soc.srcs/sources_1/imports/src/soc/uncore/gpio/gpio_defines.v
}
set_property file_type "Verilog Header" [get_files D:/uni/fyp/version8/muslim_soc/muslim_soc.srcs/sources_1/imports/src/soc/uncore/i2c/rtl/i2c_master_defines.v]
set_property file_type "Verilog Header" [get_files D:/uni/fyp/version8/muslim_soc/muslim_soc.srcs/sources_1/imports/src/soc/uncore/ptc/ptc_defines.v]
set_property file_type "Verilog Header" [get_files D:/uni/fyp/version8/muslim_soc/muslim_soc.srcs/sources_1/imports/src/soc/uncore/uart/uart_defines.v]
set_property file_type "Verilog Header" [get_files D:/uni/fyp/version8/muslim_soc/muslim_soc.srcs/sources_1/imports/src/soc/uncore/gpio/gpio_defines.v]
read_verilog -library xil_defaultlib -sv {
  {D:/uni/fyp/version8/muslim_soc/muslim_soc.srcs/sources_1/imports/main interface/IMAX.sv}
  {D:/uni/fyp/version8/muslim_soc/muslim_soc.srcs/sources_1/imports/main interface/IMCU.sv}
  D:/uni/fyp/version8/muslim_soc/muslim_soc.srcs/sources_1/new/PE_Tiles_50.sv
  D:/uni/fyp/version8/muslim_soc/muslim_soc.srcs/sources_1/imports/src/soc/core/lib.sv
  D:/uni/fyp/version8/muslim_soc/muslim_soc.srcs/sources_1/imports/src/soc/core/alignment_units.sv
  D:/uni/fyp/version8/muslim_soc/muslim_soc.srcs/sources_1/imports/src/soc/core/alu.sv
  D:/uni/fyp/version8/muslim_soc/muslim_soc.srcs/sources_1/imports/src/soc/core/alu_control.sv
  D:/uni/fyp/version8/muslim_soc/muslim_soc.srcs/sources_1/imports/src/soc/core/atomic_extension.sv
  D:/uni/fyp/version8/muslim_soc/muslim_soc.srcs/sources_1/imports/src/soc/core/branch_controller.sv
  D:/uni/fyp/version8/muslim_soc/muslim_soc.srcs/sources_1/imports/src/soc/uncore/clint/clint_top.sv
  D:/uni/fyp/version8/muslim_soc/muslim_soc.srcs/sources_1/imports/src/soc/uncore/clint/clint_wb.sv
  D:/uni/fyp/version8/muslim_soc/muslim_soc.srcs/sources_1/imports/src/soc/core/common_pkg.sv
  D:/uni/fyp/version8/muslim_soc/muslim_soc.srcs/sources_1/imports/src/soc/core/control_unit.sv
  D:/uni/fyp/version8/muslim_soc/muslim_soc.srcs/sources_1/imports/src/soc/debug/debug_pkg.sv
  D:/uni/fyp/version8/muslim_soc/muslim_soc.srcs/sources_1/imports/src/soc/core/core_dbg_fsm.sv
  D:/uni/fyp/version8/muslim_soc/muslim_soc.srcs/sources_1/imports/src/soc/sev-seg-controller/counter_n_bit.sv
  D:/uni/fyp/version8/muslim_soc/muslim_soc.srcs/sources_1/imports/src/soc/core/crypto/crypto_alu_mux.sv
  D:/uni/fyp/version8/muslim_soc/muslim_soc.srcs/sources_1/imports/src/soc/core/crypto/crypto_bitmanip_lib.sv
  D:/uni/fyp/version8/muslim_soc/muslim_soc.srcs/sources_1/imports/src/soc/core/crypto/crypto_unit.sv
  D:/uni/fyp/version8/muslim_soc/muslim_soc.srcs/sources_1/imports/src/soc/core/csr_file.sv
  D:/uni/fyp/version8/muslim_soc/muslim_soc.srcs/sources_1/imports/src/soc/core/data_mem.sv
  D:/uni/fyp/version8/muslim_soc/muslim_soc.srcs/sources_1/imports/src/soc/core/data_path.sv
  D:/uni/fyp/version8/muslim_soc/muslim_soc.srcs/sources_1/imports/src/soc/debug/debug_top.sv
  D:/uni/fyp/version8/muslim_soc/muslim_soc.srcs/sources_1/imports/src/soc/sev-seg-controller/decoder.sv
  D:/uni/fyp/version8/muslim_soc/muslim_soc.srcs/sources_1/imports/src/soc/core/decompressor.sv
  D:/uni/fyp/version8/muslim_soc/muslim_soc.srcs/sources_1/imports/src/soc/core/div.sv
  D:/uni/fyp/version8/muslim_soc/muslim_soc.srcs/sources_1/imports/src/soc/debug/dm.sv
  D:/uni/fyp/version8/muslim_soc/muslim_soc.srcs/sources_1/imports/src/soc/debug/dtm.sv
  D:/uni/fyp/version8/muslim_soc/muslim_soc.srcs/sources_1/imports/src/soc/core/exception_encoder.sv
  D:/uni/fyp/version8/muslim_soc/muslim_soc.srcs/sources_1/imports/src/soc/core/forwarding_unit.sv
  D:/uni/fyp/version8/muslim_soc/muslim_soc.srcs/sources_1/imports/src/soc/uncore/gpio/gpio_top.sv
  D:/uni/fyp/version8/muslim_soc/muslim_soc.srcs/sources_1/imports/src/soc/core/hazard_controller.sv
  D:/uni/fyp/version8/muslim_soc/muslim_soc.srcs/sources_1/imports/src/soc/core/iadu.sv
  D:/uni/fyp/version8/muslim_soc/muslim_soc.srcs/sources_1/imports/src/soc/core/imm_gen.sv
  D:/uni/fyp/version8/muslim_soc/muslim_soc.srcs/sources_1/imports/src/soc/io_mux.sv
  D:/uni/fyp/version8/muslim_soc/muslim_soc.srcs/sources_1/imports/src/soc/core/main_control.sv
  D:/uni/fyp/version8/muslim_soc/muslim_soc.srcs/sources_1/imports/src/soc/core/mul.sv
  D:/uni/fyp/version8/muslim_soc/muslim_soc.srcs/sources_1/imports/src/soc/core/pipeline_controller.sv
  D:/uni/fyp/version8/muslim_soc/muslim_soc.srcs/sources_1/imports/src/soc/core/reg_file.sv
  D:/uni/fyp/version8/muslim_soc/muslim_soc.srcs/sources_1/imports/src/soc/core/rom.sv
  D:/uni/fyp/version8/muslim_soc/muslim_soc.srcs/sources_1/imports/src/soc/rv32i_soc.sv
  D:/uni/fyp/version8/muslim_soc/muslim_soc.srcs/sources_1/imports/src/soc/core/rv32i_top.sv
  D:/uni/fyp/version8/muslim_soc/muslim_soc.srcs/sources_1/imports/src/soc/sev-seg-controller/sev_seg_controller.sv
  D:/uni/fyp/version8/muslim_soc/muslim_soc.srcs/sources_1/imports/src/soc/sev-seg-controller/sev_seg_decoder.sv
  D:/uni/fyp/version8/muslim_soc/muslim_soc.srcs/sources_1/imports/src/soc/WishboneInterconnect/wb_intercon.sv
  D:/uni/fyp/version8/muslim_soc/muslim_soc.srcs/sources_1/imports/src/soc/WishboneInterconnect/wishbone_controller.sv
  D:/uni/fyp/version8/muslim_soc/muslim_soc.srcs/sources_1/imports/src/soc/rv32i_soc_fpga_top.sv
}
read_verilog -library xil_defaultlib {
  {D:/uni/fyp/version8/muslim_soc/muslim_soc.srcs/sources_1/imports/main interface/CELL_ARRAY.v}
  {D:/uni/fyp/version8/muslim_soc/muslim_soc.srcs/sources_1/imports/main interface/Decoder.v}
  {D:/uni/fyp/version8/muslim_soc/muslim_soc.srcs/sources_1/imports/main interface/INPUT_BUFFER.v}
  {D:/uni/fyp/version8/muslim_soc/muslim_soc.srcs/sources_1/imports/main interface/RCA_Nbit.v}
  {D:/uni/fyp/version8/muslim_soc/muslim_soc.srcs/sources_1/imports/main interface/START_FSM.v}
  {D:/uni/fyp/version8/muslim_soc/muslim_soc.srcs/sources_1/imports/main interface/Timing_Control.v}
  {D:/uni/fyp/version8/muslim_soc/muslim_soc.srcs/sources_1/imports/adder tree/adder_tree.v}
  D:/uni/fyp/version8/muslim_soc/muslim_soc.srcs/sources_1/new/adder_tree_50.v
  D:/uni/fyp/version8/muslim_soc/muslim_soc.srcs/sources_1/imports/new/clockcycle_counter.v
  {D:/uni/fyp/version8/muslim_soc/muslim_soc.srcs/sources_1/imports/main interface/dma_controller.v}
  D:/uni/fyp/version8/muslim_soc/muslim_soc.srcs/sources_1/imports/src/soc/uncore/spi/fifo4.v
  {D:/uni/fyp/version8/muslim_soc/muslim_soc.srcs/sources_1/imports/main interface/full_adder.v}
  {D:/uni/fyp/version8/muslim_soc/muslim_soc.srcs/sources_1/imports/main interface/highlayercell.v}
  D:/uni/fyp/version8/muslim_soc/muslim_soc.srcs/sources_1/imports/src/soc/uncore/i2c/rtl/i2c_master_bit_ctrl.v
  D:/uni/fyp/version8/muslim_soc/muslim_soc.srcs/sources_1/imports/src/soc/uncore/i2c/rtl/i2c_master_byte_ctrl.v
  D:/uni/fyp/version8/muslim_soc/muslim_soc.srcs/sources_1/imports/src/soc/uncore/i2c/rtl/i2c_master_top.v
  {D:/uni/fyp/version8/muslim_soc/muslim_soc.srcs/sources_1/imports/main interface/interface_decoder.v}
  {D:/uni/fyp/version8/muslim_soc/muslim_soc.srcs/sources_1/imports/main interface/lowlayercell.v}
  {D:/uni/fyp/version8/muslim_soc/muslim_soc.srcs/sources_1/imports/main interface/main_interface.v}
  {D:/uni/fyp/version8/muslim_soc/muslim_soc.srcs/sources_1/imports/main interface/multiplierNbit.v}
  D:/uni/fyp/version8/muslim_soc/muslim_soc.srcs/sources_1/imports/src/soc/uncore/ptc/ptc_top.v
  D:/uni/fyp/version8/muslim_soc/muslim_soc.srcs/sources_1/imports/src/soc/uncore/uart/raminfr.v
  D:/uni/fyp/version8/muslim_soc/muslim_soc.srcs/sources_1/imports/src/soc/uncore/spi/simple_spi_top.v
  {D:/uni/fyp/version8/muslim_soc/muslim_soc.srcs/sources_1/imports/main interface/sramcell.v}
  {D:/uni/fyp/version8/muslim_soc/muslim_soc.srcs/sources_1/imports/main interface/sramcell32bit.v}
  D:/uni/fyp/version8/muslim_soc/muslim_soc.srcs/sources_1/imports/src/soc/uncore/uart/uart_receiver.v
  D:/uni/fyp/version8/muslim_soc/muslim_soc.srcs/sources_1/imports/src/soc/uncore/uart/uart_regs.v
  D:/uni/fyp/version8/muslim_soc/muslim_soc.srcs/sources_1/imports/src/soc/uncore/uart/uart_rfifo.v
  D:/uni/fyp/version8/muslim_soc/muslim_soc.srcs/sources_1/imports/src/soc/uncore/uart/uart_sync_flops.v
  D:/uni/fyp/version8/muslim_soc/muslim_soc.srcs/sources_1/imports/src/soc/uncore/uart/uart_tfifo.v
  D:/uni/fyp/version8/muslim_soc/muslim_soc.srcs/sources_1/imports/src/soc/uncore/uart/uart_top.v
  D:/uni/fyp/version8/muslim_soc/muslim_soc.srcs/sources_1/imports/src/soc/uncore/uart/uart_transmitter.v
  D:/uni/fyp/version8/muslim_soc/muslim_soc.srcs/sources_1/imports/src/soc/uncore/uart/uart_wb.v
  D:/uni/fyp/version8/muslim_soc/muslim_soc.srcs/sources_1/imports/src/soc/WishboneInterconnect/wb_intercon_1.2.2-r1/wb_mux.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/uni/fyp/version8/muslim_soc/muslim_soc.srcs/constrs_1/imports/soc/pin-assignment.xdc
set_property used_in_implementation false [get_files D:/uni/fyp/version8/muslim_soc/muslim_soc.srcs/constrs_1/imports/soc/pin-assignment.xdc]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top rv32i_soc_fpag_top -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef rv32i_soc_fpag_top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file rv32i_soc_fpag_top_utilization_synth.rpt -pb rv32i_soc_fpag_top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
